n_epochs: 150
n_units_lstm_layers: [256, 128, 64]
# n_units_lstm_layers: [128, 64]
n_filters_dcunet: 64
learning_rate: 1e-4
batch_size: 1000
SHUFFLE_BUFFER_SIZE: 1000
concatenate_train_val_sequences: true
validation_split_proportion: 0.35
augmentation: true
# When not using cross validation send null as value
cross_validation_folds: null